[package]
name = "rlisp"
version = "0.0.1"

rust-version.workspace = true
edition.workspace = true

[dependencies]
# local crates
env.workspace = true
eval.workspace = true
expr.workspace = true
pars.workspace = true

# non-local crates
