[package]
name = "cl"
version = "0.0.0"

rust-version.workspace = true
edition.workspace = true

[dependencies]
# local crates
env.workspace  = true
err.workspace  = true
expr.workspace = true
hash.workspace = true
pars.workspace = true
pars_symb.workspace = true

# non-local crates