[package]
name = "expr"
version = "0.0.0"

rust-version.workspace = true
edition.workspace = true

[dependencies]
# local crates
err.workspace = true
hash.workspace = true
pars_symb.workspace = true

# non-local crates
