[package]
name = "env"
version = "0.0.0"

rust-version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
# local crates
err.workspace = true
expr.workspace = true
hash.workspace = true
pars_symb.workspace = true

# non-local crates
rand.workspace = true